name       : dreamchess
version    : 0.2.1_rc2
release    : 3
source     :
    - https://github.com/dreamchess/dreamchess/releases/download/0.2.1-RC2/dreamchess-0.2.1-RC2.tar.gz : a26c7281819c2e84525523d13b076301b3746ff06e484642881a9ebe5138dd94
license    : GPL-3.0-or-later
component  : games.strategy
summary    : OpenGL Chess Game
description: |
    DreamChess is an open source chess game. It comes with its own engine called Dreamer.

    Both DreamChess and Dreamer are compatible with the xboard/Winboard chess engine communication protocol. This means that DreamChess can be used with other xboard-compatible chess engines such as crafty and GNU Chess. Similarly, the Dreamer chess engine can be used with other xboard-compatible user interfaces such as XBoard/WinBoard.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(mxml)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
