name       : dreamchess
version    : 0.3.0
release    : 8
source     :
    - https://github.com/dreamchess/dreamchess/archive/0.3.0.tar.gz : b070a34acf69ed92e523902683d104abb295d78b6f37663f4668e929b9e90470
license    : GPL-3.0-or-later
component  : games.strategy
summary    : OpenGL Chess Game
description: |
    DreamChess is an open source chess game. It comes with its own engine called Dreamer.

    Both DreamChess and Dreamer are compatible with the xboard/Winboard chess engine communication protocol. This means that DreamChess can be used with other xboard-compatible chess engines such as crafty and GNU Chess. Similarly, the Dreamer chess engine can be used with other xboard-compatible user interfaces such as XBoard/WinBoard.
builddeps  :
    - pkgconfig(expat)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
